# Generated by Django 2.0.13 on 2019-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190408_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(max_length=400),
        ),
    ]
