# Generated by Django 2.0.13 on 2019-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190408_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.CharField(max_length=150),
        ),
    ]
